name: Add Utility Bill

on:
  repository_dispatch:
    types: [add_utility]

permissions:
  contents: write

jobs:
  add-utility-row:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Append to CSV
        run: |
          ELECTRIC="${{ github.event.client_payload.electric }}"
          WATER="${{ github.event.client_payload.water }}"
          TOTAL=$(awk "BEGIN {print $ELECTRIC + $WATER}")
          echo "${{ github.event.client_payload.month }},$ELECTRIC,$WATER,${{ github.event.client_payload.due_date }},$TOTAL" >> data.csv

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add data.csv
          git commit -m "Add new utility bill for ${{ github.event.client_payload.month }}"
          git push
